### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by projetolab1** [loldevs/riotapi#39]
Hi, I'm trying to connect to Brazil servers using the following code:

public static void main(String[] args){
                BasicConfigurator.configure();
        LoginQueue queue = new LoginQueue(Shard.BR);
        String authToken = queue.waitInQueueBlocking("MY_USERNAME", "MY_PASSWORD");
         Shard server = Shard.BR;  
        RtmpClient client = new DefaultRtmpClient(server.prodUrl, Shard.RTMPS_PORT, true);
        try{                     
            client.connect();   //THATS THE LINE [33]                      
        } catch(Exception e){
            e.printStackTrace();
        }
}

Them I got this error:

[main] INFO net.boreeas.riotapi.rtmp.RtmpClient  - Connecting to prod.br.lol.riotgames.com:2099
java.lang.NullPointerException
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.lambda$buildSerializableClassList$19(AmfReader.java:147)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader$$Lambda$44/1496355635.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.buildSerializableClassList(AmfReader.java:144)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.<init>(AmfReader.java:66)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.<init>(AmfReader.java:58)
	at net.boreeas.riotapi.rtmp.RtmpClient.connect(RtmpClient.java:345)
	at net.boreeas.riotapi.rtmp.RtmpClient.connect(RtmpClient.java:333)
	at br.com.lolmasters.lolmastersapiv2.LOLMastersAPIv2.main(LOLMastersAPIv2.java:33)

What I'm doing wrong? Sorry about my bad english. 

Thank you very much

**Comment by Boreeas** [comment]
Hi! What version of riotapi are you using? Did you annotate any classes as `@Serializable`?

**Comment by projetolab1** [comment]
Hi! The problem was the RiotAPI number as you suspected. Now it works but when it tries the handshake (with or without ssl) it disconnects. As far as I know Riot was blocking some RTMP access, is this the case? If it is, how can I retrive the current match (live match) information like LOLNexus and Mashaple (LegendaryAPI) without connecting to the RTMP? I suspect they use your lib.

Can you do a simple test of connection to the BR server? That way we can know if its my problem or Riot. 

PS: I kept the same code and it is only that piece of code, nothing more, only the connection attempt.

Thank you very much for your answer and I'm sorry if my english its not "that" clear. lol

**Comment by projetolab1** [comment]
--- exec-maven-plugin:1.2.1:exec (default-cli) @ LOLMastersAPIv2 ---
0 [main] ERROR net.boreeas.riotapi.Shard  - No shard data listing for tr/0.0.0.13
6769 [main] INFO net.boreeas.riotapi.rtmp.RtmpClient  - Connecting to prod.br.lol.riotgames.com:2099
Exception in thread "main" java.lang.NullPointerException
	at net.boreeas.riotapi.rtmp.RtmpClient.close(RtmpClient.java:449)
	at net.boreeas.riotapi.rtmp.RtmpClient.disconnect(RtmpClient.java:442)
	at net.boreeas.riotapi.rtmp.RtmpClient.connect(RtmpClient.java:350)
	at br.com.lolmasters.lolmastersapiv2.LOLMastersAPIv2.main(LOLMastersAPIv2.java:34)
------------------------------------------------------------------------

**Comment by Boreeas** [comment]
I think I see the issue. I'll push a new release later today/tomorrow

**Comment by Boreeas** [comment]
Alright, v1.6.0 has been released (sorry, the new rest api endpoints delayed it a bit). The NPE in connect should be fixed

**Comment by projetolab1** [comment]
Dude, you're awesome! Thank you very much!
