### ISSUE TITLE
Heartbeat Probleam

### ISSUE THREAD

**Issue by projetolab1** [loldevs/riotapi#40]
Ok, using the same basic connecting method (connect, authenticate only) I got this excpetion:

6048 [main] INFO net.boreeas.riotapi.rtmp.RtmpClient  - Login complete - account state: ENABLED
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2b40ff9c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3e08ff24[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:573)
	at net.boreeas.riotapi.rtmp.RtmpClient.authenticate(RtmpClient.java:499)
	at net.boreeas.riotapi.rtmp.RtmpClient.authenticate(RtmpClient.java:458)

**Comment by Boreeas** [comment]
Oops, damn, I see the problem. Fix is uploaded, deploy is coming soon

**Comment by projetolab1** [comment]
You're THE man!

**Comment by Boreeas** [comment]
Let's not close this until it's confirmed fixed

**Comment by Boreeas** [comment]
No more errors have been reported, I guess this can be fixed now
