### ISSUE TITLE
Error during deserialization

### ISSUE THREAD

**Issue by kngu9** [loldevs/riotapi#46]
Hey guys,

I'm having an issue whenever I'm calling client.authenticate(). It is throwing an exception:

Exception in thread "main" net.boreeas.riotapi.rtmp.RtmpException: java.io.IOException: Error during deserialization
	at net.boreeas.riotapi.rtmp.RtmpClient.sendRpcAndWait(RtmpClient.java:661)
	at net.boreeas.riotapi.rtmp.services.ClientFacadeService.getLoginDataPacket(ClientFacadeService.java:37)
	at net.boreeas.riotapi.rtmp.RtmpClient.authenticate(RtmpClient.java:495)
	at net.boreeas.riotapi.rtmp.RtmpClient.authenticate(RtmpClient.java:462)

This is the code for it:

        client = new DefaultRtmpClient(shard.prodUrl, Shard.RTMPS_PORT, true);

        String user = "";
        String pass = "";
        String authKey = new LoginQueue(shard).waitInQueueBlocking(user, pass);
        
        client.connect();
        client.authenticate(user, pass, authKey, "5.24.15_12_02_18_40");

        summonerId = client.getLoginDataPacket().getAllSummonerData().getSummoner().getSumId();
        accountId = client.getLoginDataPacket().getAllSummonerData().getSummoner().getAcctId();
        
        System.out.println("test");

**Comment by Boreeas** [comment]
Is there a "Caused by: ..." line further down in the output? The full error would be helpful

**Comment by kngu9** [comment]
There's a few:

Caused by: java.io.IOException: Error during deserialization
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.deserializeAmf0(AmfReader.java:178)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.decodeAmf0(AmfReader.java:167)
	at net.boreeas.riotapi.rtmp.RtmpPacketReader.parseInvokeOrData(RtmpPacketReader.java:293)
	at net.boreeas.riotapi.rtmp.RtmpPacketReader.lambda$parsePacket$15(RtmpPacketReader.java:259)
	at net.boreeas.riotapi.rtmp.RtmpPacketReader.parsePacket(RtmpPacketReader.java:278)
	at net.boreeas.riotapi.rtmp.RtmpPacketReader.parsePacket(RtmpPacketReader.java:257)
	at net.boreeas.riotapi.rtmp.RtmpPacketReader.readPacket(RtmpPacketReader.java:121)
	at net.boreeas.riotapi.rtmp.RtmpPacketReader.run(RtmpPacketReader.java:64)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Error during deserialization
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.deserializeAmf3(AmfReader.java:278)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.decodeAmf3(AmfReader.java:267)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.deserializeAmf0(AmfReader.java:176)
	... 8 more
Caused by: java.io.IOException: Field body/body of class net.boreeas.riotapi.rtmp.messages.FlexMessage: Error during deserialization
	at net.boreeas.riotapi.rtmp.serialization.amf3.Amf3ObjectDeserializer.deserialize(Amf3ObjectDeserializer.java:55)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.readAmf3Object(AmfReader.java:466)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.deserializeAmf3(AmfReader.java:276)
	... 10 more
Caused by: java.io.IOException: Error during deserialization
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.deserializeAmf3(AmfReader.java:278)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.decodeAmf3(AmfReader.java:267)
	at net.boreeas.riotapi.rtmp.serialization.amf3.Amf3ObjectDeserializer.deserialize(Amf3ObjectDeserializer.java:52)
	... 12 more
Caused by: com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at net.boreeas.riotapi.rtmp.serialization.TypeConverter.typecast(TypeConverter.java:219)
	at net.boreeas.riotapi.rtmp.serialization.amf3.Amf3ObjectDeserializer.setStaticField(Amf3ObjectDeserializer.java:95)
	at net.boreeas.riotapi.rtmp.serialization.amf3.Amf3ObjectDeserializer.deserialize(Amf3ObjectDeserializer.java:53)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.readAmf3Object(AmfReader.java:466)
	at net.boreeas.riotapi.rtmp.serialization.AmfReader.deserializeAmf3(AmfReader.java:276)
